import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "./store/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className="bg-zinc-50">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
