import type { Metadata } from "next";
import { Provider } from "react-redux";
import "./globals.css";
import store from "./store/store";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en" data-theme="mytheme">
        <body className="bg-zinc-50">{children}</body>
      </html>
    </Provider>
  );
}
